name: Build and Test App
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/Checkout@v3
      - 
        name: Set up support Docker container for running x86_64 virtal machines using QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: CLI plugin that extends the docker command with the full support of the features provided by Moby BuildKit builder toolkit
        uses: docker/setup-buildx-action@v2
      - 
        name: Log in to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}